export type NutrientProfile = {
  calories: number; // kcal
  protein: number; // g
  carbs: number; // g
  fat: number; // g
  fiber: number; // g
  sugar: number; // g
  sodium: number; // mg
  calcium: number; // mg
  iron: number; // mg
  potassium: number; // mg
  vitaminC: number; // mg
  vitaminA: number; // µg RAE
  vitaminD: number; // µg
  cholesterol: number; // mg
  // optional human-readable serving description
  serving?: string;
};

// Minimal food database — values are per typical serving and simplified for demo
export const FOOD_DB: Record<string, NutrientProfile> = {
  apple: {
    calories: 95,
    protein: 0.5,
    carbs: 25,
    fat: 0.3,
    fiber: 4.4,
    sugar: 19,
    sodium: 1,
    calcium: 11,
    iron: 0.2,
    potassium: 195,
    vitaminC: 8.4,
    vitaminA: 98,
    vitaminD: 0,
    cholesterol: 0,
  },
  banana: {
    calories: 105,
    protein: 1.3,
    carbs: 27,
    fat: 0.4,
    fiber: 3.1,
    sugar: 14,
    sodium: 1,
    calcium: 6,
    iron: 0.3,
    potassium: 422,
    vitaminC: 10.3,
    vitaminA: 76,
    vitaminD: 0,
    cholesterol: 0,
  },
  broccoli: {
    calories: 55,
    protein: 3.7,
    carbs: 11.2,
    fat: 0.6,
    fiber: 5.1,
    sugar: 2.2,
    sodium: 64,
    calcium: 62,
    iron: 0.7,
    potassium: 457,
    vitaminC: 81.2,
    vitaminA: 567,
    vitaminD: 0,
    cholesterol: 0,
  },
  'chicken breast': {
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    sugar: 0,
    sodium: 74,
    calcium: 11,
    iron: 0.9,
    potassium: 256,
    vitaminC: 0,
    vitaminA: 13,
    vitaminD: 0.1,
    cholesterol: 85,
  },
  'beef (ground, 100g cooked)': {
    // approximate per 100g cooked ground beef (85% lean)
    calories: 250,
    protein: 26,
    carbs: 0,
    fat: 17,
    fiber: 0,
    sugar: 0,
    sodium: 72,
    calcium: 18,
    iron: 2.6,
    potassium: 318,
    vitaminC: 0,
    vitaminA: 20,
    vitaminD: 1,
    cholesterol: 90,
  },
  'pork (chop, 100g cooked)': {
    // approximate per 100g cooked pork chop
    calories: 242,
    protein: 27,
    carbs: 0,
    fat: 13,
    fiber: 0,
    sugar: 0,
    sodium: 60,
    calcium: 10,
    iron: 0.9,
    potassium: 423,
    vitaminC: 0,
    vitaminA: 3,
    vitaminD: 1,
    cholesterol: 85,
  },
  'rice (white, 1 cup)': {
    calories: 206,
    protein: 4.3,
    carbs: 45,
    fat: 0.4,
    fiber: 0.6,
    sugar: 0.1,
    sodium: 1,
    calcium: 16,
    iron: 1.9,
    potassium: 55,
    vitaminC: 0,
    vitaminA: 0,
    vitaminD: 0,
    cholesterol: 0,
  },
  'mexican rice': {
    // approximate per 1 cup cooked (rice prepared with tomato, onion, oil)
    calories: 230,
    protein: 4.5,
    carbs: 44,
    fat: 6,
    fiber: 2.5,
    sugar: 2,
    sodium: 450,
    calcium: 20,
    iron: 1.2,
    potassium: 220,
    vitaminC: 3,
    vitaminA: 40,
    vitaminD: 0,
    cholesterol: 0,
    serving: '1 cup cooked',
  },
  'milk (1 cup)': {
    calories: 122,
    protein: 8,
    carbs: 12,
    fat: 4.8,
    fiber: 0,
    sugar: 12,
    sodium: 98,
    calcium: 276,
    iron: 0,
    potassium: 366,
    vitaminC: 0,
    vitaminA: 149,
    vitaminD: 2.9,
    cholesterol: 24,
  },
  'egg (large)': {
    calories: 78,
    protein: 6.3,
    carbs: 0.6,
    fat: 5.3,
    fiber: 0,
    sugar: 0.6,
    sodium: 62,
    calcium: 25,
    iron: 0.6,
    potassium: 63,
    vitaminC: 0,
    vitaminA: 75,
    vitaminD: 1,
    cholesterol: 186,
  },
  'bacon strip': {
    // approximate per 1 strip (about 8g)
    calories: 43,
    protein: 3,
    carbs: 0.1,
    fat: 3.3,
    fiber: 0,
    sugar: 0,
    sodium: 190,
    calcium: 2,
    iron: 0.1,
    potassium: 40,
    vitaminC: 0,
    vitaminA: 15,
    vitaminD: 0,
    cholesterol: 9,
    serving: '1 strip (~8g)',
  },
  'refried beans': {
    // approximate per 1/2 cup (122g) canned refried beans
    calories: 140,
    protein: 6,
    carbs: 20,
    fat: 3,
    fiber: 6,
    sugar: 1,
    sodium: 420,
    calcium: 40,
    iron: 2,
    potassium: 400,
    vitaminC: 1,
    vitaminA: 5,
    vitaminD: 0,
    cholesterol: 0,
    serving: '1/2 cup (canned)',
  },
  cilantro: {
    // approximate per 1/4 cup (4g) chopped cilantro
    calories: 1,
    protein: 0.1,
    carbs: 0.1,
    fat: 0,
    fiber: 0.1,
    sugar: 0,
    sodium: 1,
    calcium: 5,
    iron: 0.1,
    potassium: 8,
    vitaminC: 1.1,
    vitaminA: 35,
    vitaminD: 0,
    cholesterol: 0,
    serving: '1/4 cup chopped',
  },
  'flour tortilla': {
    // approximate per 1 medium (6") flour tortilla
    calories: 140,
    protein: 4,
    carbs: 22,
    fat: 3.5,
    fiber: 1,
    sugar: 1,
    sodium: 300,
    calcium: 80,
    iron: 1.2,
    potassium: 45,
    vitaminC: 0,
    vitaminA: 0,
    vitaminD: 0,
    cholesterol: 0,
    serving: '1 medium (6")',
  },
  'bread (slice)': {
    calories: 79,
    protein: 3.4,
    carbs: 15,
    fat: 1,
    fiber: 1.9,
    sugar: 1.5,
    sodium: 146,
    calcium: 24,
    iron: 0.8,
    potassium: 69,
    vitaminC: 0,
    vitaminA: 0,
    vitaminD: 0,
    cholesterol: 0,
  },
  'daves killer bread (slice)': {
    // approximate per slice for Dave's Killer Bread varieties
    calories: 120,
    protein: 6,
    carbs: 20,
    fat: 3.5,
    fiber: 5,
    sugar: 3,
    sodium: 160,
    calcium: 30,
    iron: 1.4,
    potassium: 80,
    vitaminC: 0,
    vitaminA: 0,
    vitaminD: 0,
    cholesterol: 0,
  },
  'cheddar cheese (1 oz)': {
    calories: 113,
    protein: 6.7,
    carbs: 0.4,
    fat: 9.4,
    fiber: 0,
    sugar: 0.1,
    sodium: 174,
    calcium: 202,
    iron: 0,
    potassium: 28,
    vitaminC: 0,
    vitaminA: 265,
    vitaminD: 0.2,
    cholesterol: 30,
  },
  'string cheese': {
    // typical mozzarella string cheese, ~28g (1 stick)
    calories: 80,
    protein: 6,
    carbs: 1,
    fat: 6,
    fiber: 0,
    sugar: 0.5,
    sodium: 150,
    calcium: 200,
    iron: 0,
    potassium: 20,
    vitaminC: 0,
    vitaminA: 150,
    vitaminD: 0.1,
    cholesterol: 20,
    serving: '1 stick (~28g)',
  },
  // Fruits (top 20 list, includes apple & banana above)
  orange: {
    calories: 62,
    protein: 1.2,
    carbs: 15.4,
    fat: 0.2,
    fiber: 3.1,
    sugar: 12.2,
    sodium: 0,
    calcium: 52,
    iron: 0.1,
    potassium: 237,
    vitaminC: 69.7,
    vitaminA: 295,
    vitaminD: 0,
    cholesterol: 0,
  },
  strawberry: {
    calories: 49,
    protein: 1,
    carbs: 11.7,
    fat: 0.5,
    fiber: 3,
    sugar: 7,
    sodium: 1,
    calcium: 24,
    iron: 0.4,
    potassium: 233,
    vitaminC: 89.4,
    vitaminA: 12,
    vitaminD: 0,
    cholesterol: 0,
  },
  grape: {
    calories: 104,
    protein: 1.1,
    carbs: 27.3,
    fat: 0.2,
    fiber: 1.4,
    sugar: 23.4,
    sodium: 2,
    calcium: 15,
    iron: 0.3,
    potassium: 288,
    vitaminC: 4.8,
    vitaminA: 66,
    vitaminD: 0,
    cholesterol: 0,
  },
  kiwi: {
    calories: 42,
    protein: 0.8,
    carbs: 10.1,
    fat: 0.4,
    fiber: 2.1,
    sugar: 6.2,
    sodium: 3,
    calcium: 34,
    iron: 0.3,
    potassium: 215,
    vitaminC: 64,
    vitaminA: 87,
    vitaminD: 0,
    cholesterol: 0,
  },
  mango: {
    calories: 99,
    protein: 1.4,
    carbs: 24.7,
    fat: 0.6,
    fiber: 2.6,
    sugar: 22.5,
    sodium: 1,
    calcium: 20,
    iron: 0.2,
    potassium: 277,
    vitaminC: 60.1,
    vitaminA: 89,
    vitaminD: 0,
    cholesterol: 0,
  },
  pineapple: {
    calories: 82,
    protein: 0.9,
    carbs: 21.7,
    fat: 0.2,
    fiber: 2.3,
    sugar: 16.3,
    sodium: 2,
    calcium: 21,
    iron: 0.5,
    potassium: 180,
    vitaminC: 78.9,
    vitaminA: 95,
    vitaminD: 0,
    cholesterol: 0,
  },
  pear: {
    calories: 101,
    protein: 0.6,
    carbs: 27,
    fat: 0.2,
    fiber: 5.5,
    sugar: 17,
    sodium: 1,
    calcium: 12,
    iron: 0.2,
    potassium: 206,
    vitaminC: 7,
    vitaminA: 12,
    vitaminD: 0,
    cholesterol: 0,
  },
  peach: {
    calories: 59,
    protein: 1.4,
    carbs: 14.7,
    fat: 0.4,
    fiber: 2.3,
    sugar: 11.2,
    sodium: 0,
    calcium: 9,
    iron: 0.4,
    potassium: 190,
    vitaminC: 6.6,
    vitaminA: 16,
    vitaminD: 0,
    cholesterol: 0,
  },
  cherry: {
    calories: 97,
    protein: 1.6,
    carbs: 25,
    fat: 0.3,
    fiber: 3,
    sugar: 20,
    sodium: 0,
    calcium: 18,
    iron: 0.5,
    potassium: 259,
    vitaminC: 10.8,
    vitaminA: 64,
    vitaminD: 0,
    cholesterol: 0,
  },
  watermelon: {
    calories: 46,
    protein: 0.9,
    carbs: 11.6,
    fat: 0.2,
    fiber: 0.6,
    sugar: 9.4,
    sodium: 1,
    calcium: 11,
    iron: 0.2,
    potassium: 170,
    vitaminC: 12.5,
    vitaminA: 28,
    vitaminD: 0,
    cholesterol: 0,
  },
  cantaloupe: {
    calories: 53,
    protein: 1.3,
    carbs: 13,
    fat: 0.3,
    fiber: 1.4,
    sugar: 12.8,
    sodium: 23,
    calcium: 9,
    iron: 0.4,
    potassium: 427,
    vitaminC: 65,
    vitaminA: 299,
    vitaminD: 0,
    cholesterol: 0,
  },
  blueberries: {
    calories: 85,
    protein: 1.1,
    carbs: 21.4,
    fat: 0.5,
    fiber: 3.6,
    sugar: 14.7,
    sodium: 1,
    calcium: 9,
    iron: 0.4,
    potassium: 114,
    vitaminC: 14.4,
    vitaminA: 54,
    vitaminD: 0,
    cholesterol: 0,
  },
  raspberries: {
    calories: 64,
    protein: 1.5,
    carbs: 14.7,
    fat: 0.8,
    fiber: 8,
    sugar: 5.4,
    sodium: 1,
    calcium: 30,
    iron: 0.8,
    potassium: 186,
    vitaminC: 32.2,
    vitaminA: 2,
    vitaminD: 0,
    cholesterol: 0,
  },
  blackberries: {
    calories: 62,
    protein: 2,
    carbs: 13.8,
    fat: 0.7,
    fiber: 7.6,
    sugar: 7,
    sodium: 1,
    calcium: 42,
    iron: 0.9,
    potassium: 233,
    vitaminC: 30.2,
    vitaminA: 25,
    vitaminD: 0,
    cholesterol: 0,
  },
  papaya: {
    calories: 55,
    protein: 0.9,
    carbs: 13.7,
    fat: 0.3,
    fiber: 2.5,
    sugar: 8.3,
    sodium: 11,
    calcium: 33,
    iron: 0.1,
    potassium: 264,
    vitaminC: 88.3,
    vitaminA: 47,
    vitaminD: 0,
    cholesterol: 0,
  },
  pomegranate: {
    calories: 72,
    protein: 1.5,
    carbs: 16,
    fat: 1,
    fiber: 3,
    sugar: 12.7,
    sodium: 3,
    calcium: 10,
    iron: 0.6,
    potassium: 205,
    vitaminC: 8.5,
    vitaminA: 7,
    vitaminD: 0,
    cholesterol: 0,
  },
  plum: {
    calories: 30,
    protein: 0.5,
    carbs: 8,
    fat: 0.2,
    fiber: 0.9,
    sugar: 7.5,
    sodium: 0,
    calcium: 6,
    iron: 0.2,
    potassium: 104,
    vitaminC: 9.5,
    vitaminA: 5,
    vitaminD: 0,
    cholesterol: 0,
  },
  tangerine: {
    calories: 47,
    protein: 0.7,
    carbs: 12,
    fat: 0.3,
    fiber: 1.8,
    sugar: 9.3,
    sodium: 2,
    calcium: 37,
    iron: 0.1,
    potassium: 166,
    vitaminC: 26.7,
    vitaminA: 34,
    vitaminD: 0,
    cholesterol: 0,
  },
  // Vegetables (top 20 list, includes broccoli above)
  carrot: {
    calories: 25,
    protein: 0.6,
    carbs: 6,
    fat: 0.1,
    fiber: 1.7,
    sugar: 2.9,
    sodium: 42,
    calcium: 20,
    iron: 0.2,
    potassium: 195,
    vitaminC: 3.6,
    vitaminA: 509,
    vitaminD: 0,
    cholesterol: 0,
  },
  spinach: {
    calories: 7,
    protein: 0.9,
    carbs: 1.1,
    fat: 0.1,
    fiber: 0.7,
    sugar: 0.1,
    sodium: 24,
    calcium: 30,
    iron: 0.8,
    potassium: 167,
    vitaminC: 8.4,
    vitaminA: 469,
    vitaminD: 0,
    cholesterol: 0,
  },
  tomato: {
    calories: 22,
    protein: 1.1,
    carbs: 4.8,
    fat: 0.2,
    fiber: 1.5,
    sugar: 3.2,
    sodium: 6,
    calcium: 11,
    iron: 0.3,
    potassium: 292,
    vitaminC: 14,
    vitaminA: 102,
    vitaminD: 0,
    cholesterol: 0,
  },
  // Roma tomato uses the same approximate profile as generic tomato
  'roma tomato': {
    calories: 22,
    protein: 1.1,
    carbs: 4.8,
    fat: 0.2,
    fiber: 1.5,
    sugar: 3.2,
    sodium: 6,
    calcium: 11,
    iron: 0.3,
    potassium: 292,
    vitaminC: 14,
    vitaminA: 102,
    vitaminD: 0,
    cholesterol: 0,
  },
  cucumber: {
    calories: 16,
    protein: 0.7,
    carbs: 3.8,
    fat: 0.1,
    fiber: 0.5,
    sugar: 1.7,
    sodium: 2,
    calcium: 16,
    iron: 0.3,
    potassium: 147,
    vitaminC: 2.8,
    vitaminA: 2,
    vitaminD: 0,
    cholesterol: 0,
  },
  'bell pepper': {
    calories: 31,
    protein: 1,
    carbs: 6,
    fat: 0.3,
    fiber: 2.1,
    sugar: 4.2,
    sodium: 3,
    calcium: 7,
    iron: 0.4,
    potassium: 211,
    vitaminC: 152,
    vitaminA: 313,
    vitaminD: 0,
    cholesterol: 0,
  },
  lettuce: {
    calories: 5,
    protein: 0.5,
    carbs: 1,
    fat: 0.1,
    fiber: 0.5,
    sugar: 0.5,
    sodium: 7,
    calcium: 13,
    iron: 0.3,
    potassium: 66,
    vitaminC: 2.8,
    vitaminA: 148,
    vitaminD: 0,
    cholesterol: 0,
  },
  kale: {
    calories: 33,
    protein: 2.9,
    carbs: 6,
    fat: 0.6,
    fiber: 1.3,
    sugar: 0.5,
    sodium: 25,
    calcium: 90,
    iron: 1.1,
    potassium: 329,
    vitaminC: 80.4,
    vitaminA: 241,
    vitaminD: 0,
    cholesterol: 0,
  },
  cauliflower: {
    calories: 25,
    protein: 2,
    carbs: 5,
    fat: 0.1,
    fiber: 2,
    sugar: 2,
    sodium: 30,
    calcium: 22,
    iron: 0.4,
    potassium: 320,
    vitaminC: 46.4,
    vitaminA: 0,
    vitaminD: 0,
    cholesterol: 0,
  },
  zucchini: {
    calories: 19,
    protein: 1.5,
    carbs: 3.5,
    fat: 0.2,
    fiber: 1,
    sugar: 2.4,
    sodium: 8,
    calcium: 21,
    iron: 0.4,
    potassium: 295,
    vitaminC: 21.1,
    vitaminA: 6,
    vitaminD: 0,
    cholesterol: 0,
  },
  eggplant: {
    calories: 35,
    protein: 0.8,
    carbs: 8.6,
    fat: 0.2,
    fiber: 2.5,
    sugar: 3.5,
    sodium: 2,
    calcium: 9,
    iron: 0.2,
    potassium: 229,
    vitaminC: 2.2,
    vitaminA: 3,
    vitaminD: 0,
    cholesterol: 0,
  },
  'sweet potato': {
    calories: 103,
    protein: 2.3,
    carbs: 24,
    fat: 0.2,
    fiber: 3.8,
    sugar: 7.4,
    sodium: 41,
    calcium: 39,
    iron: 0.8,
    potassium: 438,
    vitaminC: 3.1,
    vitaminA: 1096,
    vitaminD: 0,
    cholesterol: 0,
  },
  potato: {
    calories: 161,
    protein: 4.3,
    carbs: 36.6,
    fat: 0.2,
    fiber: 3.8,
    sugar: 1.7,
    sodium: 17,
    calcium: 20,
    iron: 1.9,
    potassium: 926,
    vitaminC: 17,
    vitaminA: 2,
    vitaminD: 0,
    cholesterol: 0,
  },
  'frozen hash brown': {
    // approximate per 1 patty (about 85g) for a seasoned frozen hash brown patty
    calories: 140,
    protein: 1.5,
    carbs: 15,
    fat: 8,
    fiber: 1.5,
    sugar: 0.5,
    sodium: 300,
    calcium: 10,
    iron: 0.6,
    potassium: 300,
    vitaminC: 8,
    vitaminA: 0,
    vitaminD: 0,
    cholesterol: 0,
    serving: '1 patty (approx 85g)',
  },
  asparagus: {
    calories: 27,
    protein: 3,
    carbs: 5.2,
    fat: 0.2,
    fiber: 2.8,
    sugar: 2.5,
    sodium: 2,
    calcium: 24,
    iron: 2.9,
    potassium: 271,
    vitaminC: 7.5,
    vitaminA: 101,
    vitaminD: 0,
    cholesterol: 0,
  },
  peas: {
    calories: 62,
    protein: 4.1,
    carbs: 11.2,
    fat: 0.2,
    fiber: 4.4,
    sugar: 4.7,
    sodium: 2,
    calcium: 18,
    iron: 0.9,
    potassium: 118,
    vitaminC: 22,
    vitaminA: 22,
    vitaminD: 0,
    cholesterol: 0,
  },
  'green beans': {
    calories: 31,
    protein: 1.8,
    carbs: 7,
    fat: 0.1,
    fiber: 3.4,
    sugar: 3.9,
    sodium: 6,
    calcium: 37,
    iron: 1,
    potassium: 211,
    vitaminC: 12.2,
    vitaminA: 690,
    vitaminD: 0,
    cholesterol: 0,
  },
  'brussels sprouts': {
    calories: 38,
    protein: 3,
    carbs: 8.9,
    fat: 0.3,
    fiber: 3.3,
    sugar: 2.2,
    sodium: 27,
    calcium: 38,
    iron: 1.2,
    potassium: 342,
    vitaminC: 75.8,
    vitaminA: 63,
    vitaminD: 0,
    cholesterol: 0,
  },
  // Fast food / common items
  burger: {
    // approximate for a typical fast-food single burger (no extras)
    calories: 500,
    protein: 25,
    carbs: 40,
    fat: 30,
    fiber: 2,
    sugar: 8,
    sodium: 800,
    calcium: 150,
    iron: 3,
    potassium: 400,
    vitaminC: 2,
    vitaminA: 200,
    vitaminD: 1,
    cholesterol: 80,
    serving: '1 burger (approx)',
  },
  'french fries': {
    // approximate for a medium serving of fast-food french fries
    calories: 365,
    protein: 4,
    carbs: 48,
    fat: 17,
    fiber: 4,
    sugar: 0.3,
    sodium: 270,
    calcium: 18,
    iron: 2,
    potassium: 800,
    vitaminC: 8,
    vitaminA: 0,
    vitaminD: 0,
    cholesterol: 0,
    serving: '1 medium order',
  },
  cheeseburger: {
    // approximate: burger + cheese slice
    calories: 550,
    protein: 27,
    carbs: 41,
    fat: 33,
    fiber: 2,
    sugar: 8,
    sodium: 900,
    calcium: 180,
    iron: 3.2,
    potassium: 420,
    vitaminC: 2,
    vitaminA: 220,
    vitaminD: 1.2,
    cholesterol: 95,
    serving: '1 cheeseburger (approx)',
  },
  'burger (no cheese)': {
    calories: 480,
    protein: 25,
    carbs: 40,
    fat: 28,
    fiber: 2,
    sugar: 8,
    sodium: 780,
    calcium: 130,
    iron: 3,
    potassium: 390,
    vitaminC: 2,
    vitaminA: 190,
    vitaminD: 0.9,
    cholesterol: 78,
    serving: '1 burger (no cheese)',
  },
  cabbage: {
    calories: 22,
    protein: 1.1,
    carbs: 5.2,
    fat: 0.1,
    fiber: 2.2,
    sugar: 2.8,
    sodium: 16,
    calcium: 36,
    iron: 0.4,
    potassium: 151,
    vitaminC: 32.6,
    vitaminA: 6,
    vitaminD: 0,
    cholesterol: 0,
  },
  mushroom: {
    calories: 15,
    protein: 2.2,
    carbs: 2.3,
    fat: 0.2,
    fiber: 0.7,
    sugar: 1.4,
    sodium: 5,
    calcium: 2,
    iron: 0.3,
    potassium: 223,
    vitaminC: 2.1,
    vitaminA: 0,
    vitaminD: 0,
    cholesterol: 0,
  },
  celery: {
    calories: 16,
    protein: 0.7,
    carbs: 3,
    fat: 0.2,
    fiber: 1.6,
    sugar: 1.4,
    sodium: 80,
    calcium: 40,
    iron: 0.2,
    potassium: 260,
    vitaminC: 3.1,
    vitaminA: 22,
    vitaminD: 0,
    cholesterol: 0,
  },
  onion: {
    calories: 44,
    protein: 1.2,
    carbs: 10.3,
    fat: 0.1,
    fiber: 1.9,
    sugar: 4.7,
    sodium: 4,
    calcium: 23,
    iron: 0.2,
    potassium: 146,
    vitaminC: 8.1,
    vitaminA: 2,
    vitaminD: 0,
    cholesterol: 0,
  },
  lemon: {
    calories: 29,
    protein: 0.9,
    carbs: 6,
    fat: 0,
    fiber: 0,
    sugar: 5,
    sodium: 4,
    calcium: 14,
    iron: 0.2,
    potassium: 150,
    vitaminC: 53,
    vitaminA: 0,
    vitaminD: 0,
    cholesterol: 0,
  },
  'lemon juice': {
    // approx per 1 tbsp (15 ml)
    calories: 4,
    protein: 0.06,
    carbs: 1.3,
    fat: 0,
    fiber: 0,
    sugar: 0.2,
    sodium: 0.6,
    calcium: 1,
    iron: 0.01,
    potassium: 11,
    vitaminC: 7.7,
    vitaminA: 1,
    vitaminD: 0,
    cholesterol: 0,
  },
  avocado: {
    // approximate per medium avocado (~150g)
    calories: 234,
    protein: 2.9,
    carbs: 12.5,
    fat: 21,
    fiber: 10,
    sugar: 1.3,
    sodium: 10,
    calcium: 18,
    iron: 1.0,
    potassium: 708,
    vitaminC: 12.8,
    vitaminA: 7,
    vitaminD: 0,
    cholesterol: 0,
  },
};

// Recommended Daily Intake (RDI) simplified for an average adult — values are approximate
export const RDI = {
  calories: 2000, // kcal
  protein: 50, // g
  carbs: 275, // g
  fat: 78, // g
  fiber: 28, // g
  sugar: 50, // g (WHO recommends <50g free sugars)
  sodium: 2300, // mg
  calcium: 1000, // mg
  iron: 18, // mg
  potassium: 3500, // mg
  vitaminC: 90, // mg
  vitaminA: 900, // µg RAE
  vitaminD: 15, // µg
  cholesterol: 300, // mg
};

export const NUTRIENT_KEYS = Object.keys(RDI) as Array<keyof typeof RDI>;

export function combineProfiles(items: string[]) {
  const total: Record<string, number> = {};
  for (const key of NUTRIENT_KEYS) total[key] = 0;

  for (const name of items) {
    const key = name.toLowerCase();
    const profile = FOOD_DB[key];
    if (!profile) continue;
    for (const k of NUTRIENT_KEYS) {
      // @ts-ignore
      total[k] += (profile[k] ?? 0) as number;
    }
  }

  return total as Record<keyof typeof RDI, number>;
}

export type ItemWithQty = { name: string; qty: number };

// Combine profiles while scaling by quantity (qty = number of servings)
export function combineProfilesWithQty(items: ItemWithQty[]) {
  const total: Record<string, number> = {};
  for (const key of NUTRIENT_KEYS) total[key] = 0;

  for (const { name, qty } of items) {
    const key = name.toLowerCase();
    const profile = FOOD_DB[key];
    if (!profile) continue;
    for (const k of NUTRIENT_KEYS) {
      // @ts-ignore
      total[k] += ((profile[k] ?? 0) as number) * qty;
    }
  }

  return total as Record<keyof typeof RDI, number>;
}

// Human-friendly display names and units for each nutrient (metric-oriented)
export const NUTRIENT_DISPLAY: Record<string, string> = {
  calories: 'Calories',
  protein: 'Protein',
  carbs: 'Carbohydrates',
  fat: 'Fat',
  fiber: 'Fiber',
  sugar: 'Sugar',
  sodium: 'Sodium',
  calcium: 'Calcium',
  iron: 'Iron',
  potassium: 'Potassium',
  vitaminC: 'Vitamin C',
  vitaminA: 'Vitamin A',
  vitaminD: 'Vitamin D',
  cholesterol: 'Cholesterol',
};

export const NUTRIENT_UNITS: Record<string, string> = {
  calories: 'kcal',
  protein: 'g',
  carbs: 'g',
  fat: 'g',
  fiber: 'g',
  sugar: 'g',
  sodium: 'mg',
  calcium: 'mg',
  iron: 'mg',
  potassium: 'mg',
  vitaminC: 'mg',
  vitaminA: 'µg',
  vitaminD: 'µg',
  cholesterol: 'mg',
};
