-- Insert white rice into the foods table
-- Run this in the Supabase SQL editor

INSERT INTO foods (
  id,
  name,
  serving,
  calories,
  protein,
  carbs,
  fat,
  fiber,
  sugar,
  sodium,
  calcium,
  iron,
  potassium,
  "vitaminC",
  "vitaminA",
  "vitaminD",
  cholesterol,
  aliases,
  metadata
) VALUES (
  'white-rice',
  'white rice',
  '1 cup cooked',
  206,
  4.3,
  45,
  0.4,
  0.6,
  0.1,
  1,
  16,
  1.9,
  55,
  0,
  0,
  0,
  0,
  ARRAY['rice', 'cooked rice', 'steamed rice'],
  '{}'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  serving = EXCLUDED.serving,
  calories = EXCLUDED.calories,
  protein = EXCLUDED.protein,
  carbs = EXCLUDED.carbs,
  fat = EXCLUDED.fat,
  fiber = EXCLUDED.fiber,
  sugar = EXCLUDED.sugar,
  sodium = EXCLUDED.sodium,
  calcium = EXCLUDED.calcium,
  iron = EXCLUDED.iron,
  potassium = EXCLUDED.potassium,
  "vitaminC" = EXCLUDED."vitaminC",
  "vitaminA" = EXCLUDED."vitaminA",
  "vitaminD" = EXCLUDED."vitaminD",
  cholesterol = EXCLUDED.cholesterol,
  aliases = EXCLUDED.aliases;